# ssl
server:
  port: 8443
  ssl:
    enabled: ${SERVER_SSL_ENABLED:false}
    key-store:  ${SERVER_SSL_KEYSTORE}
    key-store-password: ${SERVER_SSL_KEYSTORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: tomcat

spring:
  profiles: prod
